### ISSUE TITLE
Articles Sorting

### ISSUE THREAD

**Issue by wcphart** [sergiois/mod_articles_thumbnails#1]
When selecting multiple categories, the sorting is alphabetical, and not configurable.
 
I have 4 categories I am wanting to show. If category slugs are A,B,C,D, and I want to show them in order as D,C,A,B
 
Perhaps instead of a list box, its a list/table that is sortable/draggable. Then we could control oder of display. Unless I am missing how to do this already. Thanks.

**Comment by sergiois** [comment]
Hi!

The module is ready to display the articles by publish date descending.
For future versions I can add a configuration that orders what is needed.
I'll keep that in mind.

Thanks for your comment.
