### ISSUE TITLE
Image not showed

### ISSUE THREAD

**Issue by mario1935** [sergiois/mod_articles_thumbnails#2]
Hi,
I'm testing your extension in local using wamp server, Apache Version : 2.4.9 PHP Version : 5.5.12.
I have a problem, in configuration  if I use  Show content -> Part of content, image is not showed. I try Intro and full but nothing happen. If I use Intro text option image is showed but all page text too...
Site template is shaper helix3 and page is build with JSN PageBuilder free.
Thanks.

**Comment by sergiois** [comment]
Hi Mario,
I'm going to do the test with the configuration that you indicate. I'll tell you something as soon as I have information.
Thanks for your comment.

**Comment by sergiois** [comment]
Hello again Mario,
I just tested the module in a site with SP Page Builder and it works correctly with the indicated configuration.

Show title: Yes
Link title: Yes
Show content: Part of content
Text size: 100
Show image: Intro image
Link image: Yes
Show "read more": No

Review the articles you show in the module to see if they have images in the native Joomla fields: Intro Image and Full Article Image.
Be careful with how you treat articles in Helix and Blog Options.
