### ISSUE TITLE
how to set column  

### ISSUE THREAD

**Issue by lungkao** [sergiois/mod_articles_thumbnails#3]
i can't set column   on module i use yootheme pro uikit 3 

http://argame.in.th/

**Comment by sergiois** [comment]
Hi!
Yootheme pro uikit 3 no está soportado por el módulo.
Puedes probar con la configuración Bootstrap 2 si tu plantilla tiene activado este check.
I'm working to make it work correctly with this version of Yootheme.

**Comment by sergiois** [comment]
Thanks to @carcam the module is compatible with version 3 of UiKit
