### ISSUE TITLE
Ordering

### ISSUE THREAD

**Issue by jordisorts** [sergiois/mod_articles_thumbnails#6]
Hello,

It would be a good option to order, as in the com_content, the option of the order of the articles.

**Comment by sergiois** [comment]
Hi Jordi,
The next version will have this option.

**Comment by jordisorts** [comment]
Great Sergio !

Do you know when the next version will be ?

**Comment by sergiois** [comment]
ASAP ;-)
Maybe next week.

**Comment by jordisorts** [comment]
Great Sergio ;)

**Comment by sergiois** [comment]
Hi @vieri!! 
New version is available

**Comment by jordisorts** [comment]
Thanks @sergiois !!! I will check.
